version: "3"

services:
  wordpress:
    build: .
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DEBUG: 1
    depends_on:
      - "mysql"
    ports:
      - 8080:80
    volumes:
      - "wp:/var/www/html:rw"
      - ".:/var/www/html/wp-content/plugins/conditional-featured-image:ro"
      - "./addon-php.ini:/usr/local/etc/php/conf.d/addon-php.ini:ro"

  mysql:
    image: "mariadb:latest"
    volumes:
      - "db:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""

  phpmyadmin:
    image: "phpmyadmin:latest"
    ports:
      - 8081:80
    environment:
        PMA_HOST: "mysql"
        PMA_PORT: "3306"
        PMA_USER: "root"
        PMA_PASSWORD: ""
        UPLOAD_LIMIT: 1G
    depends_on:
        - "mysql"

volumes:
  wp:
  db:
